# -*- coding: utf-8 -*-
"""Untitled258.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M0wHzKUP5lv4x1F09dRAJovVyjFzl02Y
"""



import os
import ipywidgets as widgets
from IPython.display import display
from google import genai

MODEL_ID = "gemini-3.6-flash"

PRESET_PROMPTS = [
    "--- Оберіть готовий промт ---",
    "1. Зроби детальний таймлайн та короткий зміст цього відео.",
    "2. Знайди у цьому відео всі моменти, де згадуються помилки або проблеми.",
    "3. Переклади основну суть того, про що йдеться у відео, простою мовою.",
    "4. Випиши головні тези та висновки з цього відеоматеріалу.",
    "5. Проаналізуй візуальний ряд та розкажи, що саме відбувається на екрані.",
    "6. Зроби перевірку фактів та надай критичний аналіз почутого у відео.",
    "7. Напиши короткий пост для соцмереж на основі цього відео.",
    "8. Сформуй 5 цікавих запитань для дискусії за цим відео.",
    "9. Виділи ключові терміни чи поняття, які використовуються у відео, і поясни їх.",
    "10. Оціни тон і настрій розмовного та візуального супроводу у відео."
]

api_key_input = widgets.Password(
    value='',
    placeholder='Введіть ваш Gemini API ключ тут',
    description='API Key:',
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='650px')
)

prompt_dropdown = widgets.Dropdown(
    options=PRESET_PROMPTS,
    value=PRESET_PROMPTS[0],
    description='Промти:',
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='650px')
)

prompt_text_area = widgets.Textarea(
    value='',
    placeholder="Текст промта з'явиться тут при виборі зі списку або введіть свій...",
    description='Запит:',
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='650px', height='100px')
)

def on_prompt_change(change):
    if change['type'] == 'change' and change['name'] == 'value':
        selected = change['new']
        if selected != PRESET_PROMPTS[0]:
            clean_text = selected.split(". ", 1)[1] if ". " in selected else selected
            prompt_text_area.value = clean_text

prompt_dropdown.observe(on_prompt_change)

upload_btn = widgets.FileUpload(
    accept='video/*',
    multiple=False,
    description='Обрати відео'
)
upload_status = widgets.Label(value='Відеофайл не обрано')

def on_upload_change(change):
    if upload_btn.value:
        try:
            if isinstance(upload_btn.value, dict):
                filename = list(upload_btn.value.keys())[0]
            else:
                filename = upload_btn.value[0]['name']
            upload_status.value = f'✅ Обрано файл: {filename}'
        except Exception:
            upload_status.value = '✅ Файл завантажено'

upload_btn.observe(on_upload_change, names='value')

video_url_input = widgets.Text(
    value='',
    placeholder='Або введіть посилання на відео (URL)',
    description='Відео URL:',
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='650px')
)

send_button = widgets.Button(
    description='🚀 Надіслати в Gemini (Відео + Промт)',
    button_style='success',
    layout=widgets.Layout(width='650px', height='45px')
)

output_area = widgets.Output(layout=widgets.Layout(border='1px solid #ccc', width='650px', padding='10px'))

def on_send_clicked(b):
    output_area.clear_output()
    with output_area:
        api_key = api_key_input.value.strip()
        if not api_key:
            print("❌ Помилка: Введіть ваш Gemini API ключ у поле зверху!")
            return

        try:
            client = genai.Client(api_key=api_key)
        except Exception as e:
            print(f"❌ Помилка ініціалізації клієнта Gemini: {e}")
            return

        prompt_val = prompt_text_area.value.strip()
        url_val = video_url_input.value.strip()

        contents = []
        local_file_path = None

        if upload_btn.value:
            try:
                if isinstance(upload_btn.value, dict):
                    filename = list(upload_btn.value.keys())[0]
                    file_content = upload_btn.value[filename]['content']
                else:
                    filename = upload_btn.value[0]['name']
                    file_content = upload_btn.value[0]['content']

                local_file_path = f"/tmp/{filename}"
                with open(local_file_path, "wb") as f:
                    f.write(file_content)
            except Exception as ex:
                print(f"Помилка читання файлу: {ex}")

        if local_file_path and os.path.exists(local_file_path):
            print(f"⏳ Завантаження відео на сервери Gemini...")
            video_ref = client.files.upload(file=local_file_path)
            contents.append(video_ref)
        elif url_val:
            contents.append(url_val)

        if prompt_val:
            contents.append(prompt_val)
        else:
            default_prompt = "Опиши детально що відбувається у цьому відео."
            contents.append(default_prompt)

        print("📤 Надсилання запиту до Gemini...")
        try:
            response = client.models.generate_content(
                model=MODEL_ID,
                contents=contents
            )
            print("\n🤖 ВІДПОВІДЬ GEMINI:\n")
            print(response.text)
        except Exception as e:
            print(f"❌ Помилка API Gemini: {e}")

send_button.on_click(on_send_clicked)

main_ui = widgets.VBox([
    widgets.HTML("<h3>Система аналізу відео на основі штучного інтелекту</h3>"),
    api_key_input,
    widgets.HTML("<hr>"),
    prompt_dropdown,
    prompt_text_area,
    widgets.HTML("<hr>"),
    widgets.HBox([upload_btn, upload_status]),
    video_url_input,
    widgets.HTML("<hr>"),
    send_button,
    widgets.HTML("<h4>Вікно чату / результату:</h4>"),
    output_area
])

display(main_ui)